Adds better logging to downloads

diff --git a/bin/installJDK8 b/bin/installJDK8
--- a/bin/installJDK8
+++ b/bin/installJDK8
@@ -3,14 +3,22 @@
 # download and unzip jdk8 to ~/jvm directory
 
 set -euo pipefail
-echo "Setup JDK 1.8u161"
+JDK_RELEASE=161
+echo "Setup JDK 1.8u$JDK_RELEASE"
 mkdir -p ~/jvm
 pushd ~/jvm > /dev/null
-if [ ! -d "jdk1.8.0_161" ]; then
-  wget --quiet --continue --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
-  tar xzf jdk-8u161-linux-x64.tar.gz
-  rm jdk-8u161-linux-x64.tar.gz
+
+if [ ! -d "jdk1.8.0_$JDK_RELEASE" ]; then
+  {
+    wget --quiet --continue --header "Cookie: oraclelicense=accept-securebackup-cookie" http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/jdk-8u161-linux-x64.tar.gz
+  } || {
+    echo "failed to download JDK 1.8u$JDK_RELEASE"
+    exit 1
+  }
+  tar xzf jdk-8u$JDK_RELEASE-linux-x64.tar.gz
+  rm jdk-8u$JDK_RELEASE-linux-x64.tar.gz
 fi
 popd > /dev/null
-export JAVA_HOME=~/jvm/jdk1.8.0_161
+export JAVA_HOME=~/jvm/jdk1.8.0_$JDK_RELEASE
 export PATH=$JAVA_HOME/bin:$PATH
+echo "JDK 1.8u$JDK_RELEASE installed"
diff --git a/bin/installMaven b/bin/installMaven
--- a/bin/installMaven
+++ b/bin/installMaven
@@ -5,14 +5,20 @@
 
 set -euo pipefail
 
-echo "Setup Maven"
+echo "Setup Maven $1"
 mkdir -p ~/maven
 pushd ~/maven > /dev/null
 if [ ! -d "apache-maven-$1" ]; then
   echo "Download Maven $1"
-  wget --quiet --continue  "https://archive.apache.org/dist/maven/maven-3/$1/binaries/apache-maven-$1-bin.zip" 
+  {
+    wget --quiet --continue  "https://archive.apache.org/dist/maven/maven-3/$1/binaries/apache-maven-$1-bin.zip" 
+  } || {
+    echo "failed to download Maven $1"
+    exit 1
+  }
   unzip "apache-maven-$1-bin.zip" -d ~/maven > /dev/null
 fi
 popd > /dev/null
 export M2_HOME=~/maven/apache-maven-$1
 export PATH=$M2_HOME/bin:$PATH
+echo "Maven $1 installed"
