no dory analysis for release branch

diff --git a/bin/regular_mvn_build_deploy_analyze b/bin/regular_mvn_build_deploy_analyze
--- a/bin/regular_mvn_build_deploy_analyze
+++ b/bin/regular_mvn_build_deploy_analyze
@@ -11,7 +11,7 @@
 
 set -euo pipefail
 
-if [ "${TRAVIS_BRANCH}" == "master" ] || [[ "${TRAVIS_BRANCH}" == "branch-"* ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
+if [ "${TRAVIS_BRANCH}" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
   echo '======= Build, deploy and analyze master'
 
   # Fetch all commit history so that SonarQube has exact blame information
@@ -25,6 +25,27 @@ if [ "${TRAVIS_BRANCH}" == "master" ] || [[ "${TRAVIS_BRANCH}" == "branch-"* ]] 
   # purge of release data
   CURRENT_VERSION=`maven_expression "project.version"`
 
+  set_maven_build_version $TRAVIS_BUILD_NUMBER
+  
+  export MAVEN_OPTS="-Xmx1536m -Xms128m"
+  mvn org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar \
+      -Pcoverage-per-test,deploy-sonarsource \
+      -Dmaven.test.redirectTestOutputToFile=false \
+      -Dsonar.host.url=$SONAR_HOST_URL \
+      -Dsonar.login=$SONAR_TOKEN \
+      -Dsonar.projectVersion=$CURRENT_VERSION \
+      -B -e -V
+
+elif [[ "${TRAVIS_BRANCH}" == "branch-"* ]] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
+  # no dory analysis on release branch
+
+  # Fetch all commit history so that SonarQube has exact blame information
+  # for issue auto-assignment
+  # This command can fail with "fatal: --unshallow on a complete repository does not make sense" 
+  # if there are not enough commits in the Git repository (even if Travis executed git clone --depth 50).
+  # For this reason errors are ignored with "|| true"
+  git fetch --unshallow || true 
+  
   if [[ $CURRENT_VERSION =~ "-SNAPSHOT" ]]; then
     echo "======= Found SNAPSHOT version ======="
     # Do not deploy a SNAPSHOT version but the release version related to this build
@@ -34,13 +55,9 @@ if [ "${TRAVIS_BRANCH}" == "master" ] || [[ "${TRAVIS_BRANCH}" == "branch-"* ]] 
   fi
 
   export MAVEN_OPTS="-Xmx1536m -Xms128m"
-  mvn org.jacoco:jacoco-maven-plugin:prepare-agent deploy sonar:sonar \
-      -Pcoverage-per-test,deploy-sonarsource \
-      -Dmaven.test.redirectTestOutputToFile=false \
-      -Dsonar.host.url=$SONAR_HOST_URL \
-      -Dsonar.login=$SONAR_TOKEN \
-      -Dsonar.projectVersion=$CURRENT_VERSION \
-      -B -e -V
+  mvn deploy \
+        -Pdeploy-sonarsource \
+        -B -e -V      
 
 elif [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ -n "${GITHUB_TOKEN:-}" ]; then
   echo '======= Build and analyze pull request, deploy'
