Always fetch all commit history

diff --git a/bin/regular_mvn_build_deploy_analyze b/bin/regular_mvn_build_deploy_analyze
--- a/bin/regular_mvn_build_deploy_analyze
+++ b/bin/regular_mvn_build_deploy_analyze
@@ -11,15 +11,15 @@
 
 set -euo pipefail
 
+# Fetch all commit history so that SonarQube has exact blame information
+# for issue auto-assignment
+# This command can fail with "fatal: --unshallow on a complete repository does not make sense" 
+# if there are not enough commits in the Git repository (even if Travis executed git clone --depth 50).
+# For this reason errors are ignored with "|| true"
+git fetch --unshallow || true
+
 if [ "${TRAVIS_BRANCH}" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
   echo '======= Build, deploy and analyze master'
-
-  # Fetch all commit history so that SonarQube has exact blame information
-  # for issue auto-assignment
-  # This command can fail with "fatal: --unshallow on a complete repository does not make sense" 
-  # if there are not enough commits in the Git repository (even if Travis executed git clone --depth 50).
-  # For this reason errors are ignored with "|| true"
-  git fetch --unshallow || true
 
   # Analyze with SNAPSHOT version as long as SQ does not correctly handle
   # purge of release data
